version: "3.9"

services:
  db:
    image: postgres:15
    container_name: superhero-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Jeet@#$%105520"
      POSTGRES_DB: superhero
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: superhero-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:Jeet%40%23%24%25105520@db:5432/superhero?schema=public"

  frontend:
    build: ./frontend
    container_name: superhero-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data:
